"""
ARCS — Rebuild Physics Table
Run this ONCE to fix the HIGH-angle solution gap.

WHAT THIS FIXES
───────────────
Your range_table_physics.csv was generated by the old pipeline before
dual-trajectory support was added. It has:
    HIGH-angle entries: 0

After this script:
    HIGH-angle entries: ~12,000+  (all reachable cells get BOTH solutions)

YOUR CORRECTIONS FILE IS NOT TOUCHED.
All engagement history and learned corrections are preserved.

HOW LONG
────────
Full resolution (~38,610 cells): 25–35 seconds on a modern CPU.
After this runs once, you never need to run it again unless you
change the range/height/v0 grid in constants.py.

USAGE
─────
    python rebuild_physics.py               # full resolution (recommended)
    python rebuild_physics.py --fast        # coarser grid, ~5s, for testing
    python rebuild_physics.py --validate    # rebuild + deep accuracy sweep
"""

import sys
import time
import shutil
import argparse
import numpy as np
from pathlib import Path

# ── Parse flags ──────────────────────────────────────────────────────────────
parser = argparse.ArgumentParser(description="Rebuild ARCS physics table")
parser.add_argument("--fast",     action="store_true",
                    help="Coarse grid for quick testing (~5s) — "
                         "writes to data/range_table_physics_fast.csv "
                         "by default to avoid overwriting production data")
parser.add_argument("--validate", action="store_true",
                    help="Run deep accuracy validation after rebuild")
parser.add_argument("--physics-path",     default=None,
                    help="Override output path (default: production path for full, "
                         "data/range_table_physics_fast.csv for --fast)")
parser.add_argument("--corrections-path", default="data/range_table_corrections.csv")
args = parser.parse_args()

# Default path depends on mode: --fast never touches production table by default
if args.physics_path is None:
    args.physics_path = ("data/range_table_physics_fast.csv"
                         if args.fast else "data/range_table_physics.csv")

# ── Imports after path-arg so help works without deps ────────────────────────
from physics.range_table    import RangeTable
from physics.ballistic_solver import BallisticSolver
from physics.constants        import (RT_RANGE_STEPS, RT_HEIGHT_STEPS,
                                       RT_V0_STEPS)

PHYSICS_PATH = args.physics_path
CORR_PATH    = args.corrections_path

print("=" * 62)
print("  ARCS — Physics Table Rebuild")
print("=" * 62)

# ── Step 0: check what we have now ───────────────────────────────────────────
rt_check = RangeTable(PHYSICS_PATH, CORR_PATH)
high_before = 0
if Path(PHYSICS_PATH).exists():
    rt_check.load_physics(verbose=False)
    high_before = int(rt_check._physics_df["has_high_solution"].sum()) \
                  if "has_high_solution" in rt_check._physics_df.columns else 0
    total_before = len(rt_check._physics_df)
    print(f"\n  Current table:")
    print(f"    Rows            : {total_before:,}")
    print(f"    HIGH solutions  : {high_before:,}  ← this is the problem")
else:
    print(f"\n  No existing table found — will generate from scratch.")

# ── Step 1: backup ───────────────────────────────────────────────────────────
if Path(PHYSICS_PATH).exists():
    from datetime import datetime as _dt
    _stamp = _dt.now().strftime("%Y%m%d_%H%M%S")
    backup = PHYSICS_PATH.replace(".csv", f"_backup_{_stamp}.csv")
    shutil.copy(PHYSICS_PATH, backup)
    print(f"\n  Backed up → {backup}")

# ── Step 2: choose grid resolution ───────────────────────────────────────────
if args.fast:
    range_steps  = np.arange(50, 455, 50)     # 9 values
    height_steps = np.arange(-20, 55, 15)     # 5 values
    v0_steps     = np.arange(50, 305, 50)     # 6 values
    print(f"\n  Mode: FAST (coarse grid for testing)")
else:
    range_steps  = RT_RANGE_STEPS              # 99 values  (10–500m, step 5)
    height_steps = RT_HEIGHT_STEPS             # 15 values (-20–50m, step 5)
    v0_steps     = RT_V0_STEPS                 # 26 values  (50–300m/s, step 10)
    print(f"\n  Mode: FULL resolution (production quality)")

total_cells = len(range_steps) * len(height_steps) * len(v0_steps)
print(f"  Grid: {len(range_steps)} ranges × {len(height_steps)} heights "
      f"× {len(v0_steps)} velocities = {total_cells:,} cells")
print(f"  Both LOW and HIGH solutions computed per cell.")

# ── Step 3: generate ─────────────────────────────────────────────────────────
print(f"\n  Generating... (this takes ~{max(5, int(total_cells/1200))}s)")
rt = RangeTable(PHYSICS_PATH, CORR_PATH)

t0 = time.time()
rt.generate_physics(
    range_steps  = range_steps,
    height_steps = height_steps,
    v0_steps     = v0_steps,
    verbose      = True,
    force        = True,
)
elapsed = time.time() - t0

# ── Step 4: report ───────────────────────────────────────────────────────────
df        = rt._physics_df
high_after  = int(df["has_high_solution"].sum())
low_reach   = int(df["reachable"].sum())
high_frac   = high_after / max(1, low_reach) * 100

print(f"\n  ─── Rebuild complete in {elapsed:.1f}s ───")
print(f"  Total cells         : {len(df):,}")
print(f"  LOW  reachable      : {low_reach:,}")
print(f"  HIGH solutions      : {high_after:,}  ({high_frac:.0f}% of reachable)")
print(f"  HIGH before → after : {high_before:,} → {high_after:,}")

# ── Step 5: interpolation quality check ──────────────────────────────────────
# Tests the raw interpolators (not lookup()) — lookup() uses the direct solver
# and is always exact. These results show grid quality for diagnostics only.
print(f"\n  Checking interpolation grid quality (diagnostic)...")
solver  = BallisticSolver()
rng     = np.random.default_rng(0)
errors_low, errors_high, checked = [], [], 0

for _ in range(30):
    R  = float(rng.uniform(range_steps.min(), range_steps.max()))
    H  = float(rng.uniform(height_steps.min(), height_steps.max()))
    v0 = float(rng.uniform(v0_steps.min(), v0_steps.max()))

    sol_l = solver.solve(R, H, 0.0, v0, prefer="LOW")
    sol_h = solver.solve(R, H, 0.0, v0, prefer="HIGH")

    # Clamp to grid bounds before querying interpolators directly.
    pt = np.array([[
        float(np.clip(R,  rt._ranges[0],  rt._ranges[-1])),
        float(np.clip(H,  rt._heights[0], rt._heights[-1])),
        float(np.clip(v0, rt._v0s[0],     rt._v0s[-1]))
    ]])

    if sol_l.reachable and rt._interp_pitch is not None:
        interp_p = float(rt._interp_pitch(pt)[0])
        errors_low.append(abs(sol_l.turret_pitch_deg - interp_p))

    if sol_h.reachable and sol_h.solution_type == "HIGH" \
            and rt._interp_pitch_high is not None:
        interp_ph = float(rt._interp_pitch_high(pt)[0])
        if not np.isnan(interp_ph):
            errors_high.append(abs(sol_h.turret_pitch_deg - interp_ph))
            interp_pl = float(rt._interp_pitch(pt)[0])
            if not np.isnan(interp_pl) and interp_ph <= interp_pl - 1.0:
                print(f"  [WARN] HIGH interp {interp_ph:.1f}° ≤ LOW {interp_pl:.1f}° "
                      f"at R={R:.0f} H={H:.0f}")
    checked += 1

print(f"  Points checked      : {checked}")
if errors_low:
    print(f"  LOW  interp error   : mean={np.mean(errors_low):.4f}°  "
          f"max={np.max(errors_low):.4f}°")
if errors_high:
    print(f"  HIGH interp error   : mean={np.mean(errors_high):.4f}°  "
          f"max={np.max(errors_high):.4f}°")
else:
    print(f"  HIGH interp checks  : no HIGH solutions in random sample region")

low_ok  = not errors_low  or np.max(errors_low)  < 2.0
high_ok = not errors_high or np.max(errors_high) < 2.0
print(f"  LOW  grid quality   : {'✓' if low_ok  else '⚠ degraded (lookup uses direct solver)'}")
print(f"  HIGH grid quality   : {'✓' if high_ok else '⚠ degraded (lookup uses direct solver)'}")

# ── Step 6: deep validation (optional) ───────────────────────────────────────
# Tests raw interpolation quality across 200 random points. lookup() itself
# uses the direct solver and is always exact — these results are diagnostic.
if args.validate:
    print(f"\n  ─── Deep interpolation quality sweep (200 points) ───")
    v_errors_l, v_errors_h, v_failures = [], [], []

    for _ in range(200):
        R  = float(rng.uniform(range_steps.min(), range_steps.max()))
        H  = float(rng.uniform(height_steps.min(), height_steps.max()))
        v0 = float(rng.uniform(v0_steps.min(), v0_steps.max()))

        sol_l = solver.solve(R, H, 0.0, v0, prefer="LOW")
        sol_h = solver.solve(R, H, 0.0, v0, prefer="HIGH")

        pt = np.array([[
            float(np.clip(R,  rt._ranges[0],  rt._ranges[-1])),
            float(np.clip(H,  rt._heights[0], rt._heights[-1])),
            float(np.clip(v0, rt._v0s[0],     rt._v0s[-1]))
        ]])

        if sol_l.reachable and rt._interp_pitch is not None:
            e = abs(sol_l.turret_pitch_deg - float(rt._interp_pitch(pt)[0]))
            v_errors_l.append(e)
            if e > 3.0:
                v_failures.append(f"LOW R={R:.0f} H={H:.0f} v0={v0:.0f}: {e:.2f}°")

        if sol_h.reachable and sol_h.solution_type == "HIGH" \
                and rt._interp_pitch_high is not None:
            interp_ph = float(rt._interp_pitch_high(pt)[0])
            if not np.isnan(interp_ph):
                e = abs(sol_h.turret_pitch_deg - interp_ph)
                v_errors_h.append(e)
                if e > 3.0:
                    v_failures.append(f"HIGH R={R:.0f} H={H:.0f} v0={v0:.0f}: {e:.2f}°")

    print(f"  200 random points checked.")
    if v_errors_l:
        print(f"  LOW  : mean={np.mean(v_errors_l):.4f}°  "
              f"p95={np.percentile(v_errors_l,95):.4f}°  "
              f"max={np.max(v_errors_l):.4f}°")
    if v_errors_h:
        print(f"  HIGH : mean={np.mean(v_errors_h):.4f}°  "
              f"p95={np.percentile(v_errors_h,95):.4f}°  "
              f"max={np.max(v_errors_h):.4f}°")
    if v_failures:
        print(f"  Grid cells with >3.0° interpolation error: {len(v_failures)}")
        for f in v_failures[:5]:
            print(f"    {f}")
        print(f"  (lookup() uses direct solver — these cells have no effect on accuracy)")
    else:
        print(f"  Interpolation grid: all < 3.0° error ✓")

# ── Step 7: print usage instructions ─────────────────────────────────────────
print(f"\n{'='*62}")
if high_after > 0:
    print(f"  ✓ Rebuild successful.")
    print(f"    HIGH-angle entries: {high_after:,}  (was {high_before:,})")
    print(f"\n  Now run: python pipeline.py")
    print(f"  The pipeline will use HIGH trajectory for prefer='HIGH' engagements.")
    print(f"  The ⚠ warning at startup will no longer appear.")
else:
    print(f"  ✗ No HIGH solutions found.")
    print(f"  Check that ballistic_solver.solve_both() returns HIGH solutions.")
    print(f"  Try: python -c \"from physics.ballistic_solver import *; "
          f"s=BallisticSolver(); print(s.solve_both(200,0,0,80))\"")
    print(f"{'='*62}")
    sys.exit(1)
print(f"{'='*62}")